"""0000

Revision ID: 3ac52f62bb4e
Revises:
Create Date: 2026-06-12 16:43:01.771484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import cata_log_hub.database.types

# revision identifiers, used by Alembic.
revision: str = "3ac52f62bb4e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pagefiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "path", cata_log_hub.database.types.PathType(length=1024), nullable=False
        ),
        sa.Column("original_sha256", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pagefiles")),
        sa.UniqueConstraint("path", name=op.f("uq_pagefiles__path")),
        sa.CheckConstraint("size > 0", name=op.f("ck_pagefiles__size_gt_0")),
        sa.CheckConstraint("height > 0", name=op.f("ck_pagefiles__height_gt_0")),
        sa.CheckConstraint("width > 0", name=op.f("ck_pagefiles__width_gt_0")),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("class_uid", sa.String(length=127), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("job_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "MISCONFIGURED",
                "BROKEN",
                "MISCONFIGURED_OR_BROKEN",
                "UNAVAILABLE",
                "HEALTHY",
                name="provider_status_enum",
            ),
            server_default="HEALTHY",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
        sa.UniqueConstraint("job_id", name=op.f("uq_providers__job_id")),
    )
    op.create_table(
        "catalogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "valid_since",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "valid_until",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            nullable=False,
        ),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_catalogs__provider_id__providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalogs")),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("catalog_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            cata_log_hub.database.types.UTCDatetime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["catalogs.id"],
            name=op.f("fk_pages__catalog_id__catalogs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["pagefiles.id"],
            name=op.f("fk_pages__file_id__pagefiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint(
            "catalog_id", "number", name=op.f("uq_pages__catalog_id_number")
        ),
        sa.CheckConstraint("number >= 0", name=op.f("ck_pages__number_ge_0")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pages")
    op.drop_table("catalogs")
    op.drop_table("providers")
    op.drop_table("pagefiles")
    # ### end Alembic commands ###
