services:
  cata-log-hub:
    image: dacid99/cata-log-hub:latest
    container_name: cata-log
    volumes:
      - cata-log-storage:/mnt/storage
      - cata-log-db:/mnt/db
      - cata-log-logs:/var/log/cata-log
      - cata-log-plugins:/mnt/plugins
    ports:
      - 2424:8000
    environment:
      - CATA_LOG_USERNAME=admin
      - CATA_LOG_PASSWORD=SafE_pAs5w0rd # setting no password makes authentication impossible #gitleaks:allow
      - CATA_LOG_PUBLIC_GET= # set this to make all GET endpoints unprotected
      - CATA_LOG_REQUEST_TIMEOUT=10
      - CATA_LOG_RETRY_DELAY=180
      - CATA_LOG_EXPIRATION_DAYS=14
      - CATA_LOG_LOG_LEVEL=INFO
      - CATA_LOG_LOG_FILE_BACKUP_COUNT=10
      - CATA_LOG_LOG_FILE_MAXSIZE=2097152
      - CATA_LOG_LOG_FILE_API_DEFAULT_PAGINATION_PAGE_SIZE=50
      - CATA_LOG_LOG_FILE_API_MAX_PAGINATION_PAGE_SIZE=100
      - CATA_LOG_DEV_MODE= # set this only in development
      - CATA_LOG_FORWARDED_ALLOW_IPS= # set this if you proxy
      - CATA_LOG_ROOT_PATH= # set this if you proxy with a custom location, must start with /
      - CATA_LOG_ALLOWED_HOSTS=["127.0.0.1","localhost"] # hostnames that are allowed to serve this instance
    restart: unless-stopped

volumes:
  cata-log-storage:
  cata-log-db:
  cata-log-logs:
  cata-log-plugins:
