services:
  db:
    image: postgres:latest
    container_name: cata-log-db
    volumes:
      - cata-log-db-data:/var/lib/postgresql/
      - cata-log-db-init:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=cata-log # must match cata-log-hub:DATABASE_NAME
      - POSTGRES_USER=user # must match cata-log-hub:DATABASE_USER
      - POSTGRES_PASSWORD=db_passwd # must match cata-log-hub:DATABASE_PASSWORD
      - PGADMIN_DEFAULT_PASSWORD=example
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      start_period: 20s
      start_interval: 5s
      interval: 1m
      timeout: 5s
      retries: 3

  cata-log-hub:
    image: cata-log-hub:latest
    container_name: cata-log
    volumes:
      - cata-log-storage:/mnt/storage
      - cata-log-logs:/var/log/cata-log
      - cata-log-plugins:/mnt/plugins
    ports:
      - 2424:8000
    environment:
      - CATA_LOG_PASSWORD=testwithdb1234 # gitleaks:allow
      - CATA_LOG_ALLOWED_HOSTS=["127.0.0.1","localhost", "0.0.0.0"] # hostnames that are allowed to serve this instance, must include 0.0.0.0 for healthcheck to work
      - CATA_LOG_EXTERNAL_DATABASE_URL=postgresql+pg8000://user:db_passwd@db/cata-log
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

volumes:
  cata-log-storage:
  cata-log-db-data:
  cata-log-db-init:
  cata-log-logs:
  cata-log-plugins:
