services:
  db:
    image: mariadb:latest
    container_name: cata-log-db
    volumes:
      - cata-log-db-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=cata-log # must match cata-log-hub:DATABASE_NAME
      - MARIADB_USER=user # must match cata-log-hub:DATABASE_USER
      - MARIADB_PASSWORD=db_passwd # must match cata-log-hub:DATABASE_PASSWORD
      - MARIADB_ROOT_PASSWORD=example
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 20s
      start_interval: 5s
      interval: 1m
      timeout: 5s
      retries: 3

  cata-log-hub:
    image: dacid99/cata-log-hub:latest
    container_name: cata-log
    volumes:
      - cata-log-storage:/mnt/storage
      - cata-log-logs:/var/log/cata-log
      - cata-log-plugins:/mnt/plugins
    ports:
      - 2424:8000
    environment:
      - CATA_LOG_PASSWORD=testwithdb1234 # gitleaks:allow
      - CATA_LOG_ALLOWED_HOSTS=["127.0.0.1","localhost", "0.0.0.0"] # hostnames that are allowed to serve this instance, must include 0.0.0.0 for healthcheck to work
      - CATA_LOG_EXTERNAL_DATABASE_URL=mysql+pymysql://user:db_passwd@db/cata-log
      - CATA_LOG_ALLOWED_HOSTS="127.0.0.1,localhost" # add your hostname here
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

volumes:
  cata-log-storage:
  cata-log-db-data:
  cata-log-logs:
  cata-log-plugins:
