services:
  db:
    image: postgres:latest
    container_name: cata-log-db
    volumes:
      - /path/to/cata-log-hub/postgres/:/var/lib/postgresql/
      - /path/to/cata-log-hub/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=cata-log # must match cata-log-hub:DATABASE_NAME
      - POSTGRES_USER=user # must match cata-log-hub:DATABASE_USER
      - POSTGRES_PASSWORD=db_passwd # must match cata-log-hub:DATABASE_PASSWORD
      - PGADMIN_DEFAULT_PASSWORD=example
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      start_period: 20s
      start_interval: 5s
      interval: 1m
      timeout: 5s
      retries: 3

  cata-log-hub:
    image: cata-log-hub:latest
    container_name: cata-log
    volumes:
      - /path/to/cata-log-hub/storage:/mnt/storage
      - /path/to/cata-log-hub/log:/var/log/cata-log
      - /path/to/cata-log-hub/plugins:/mnt/plugins
    ports:
      - 2424:8000
    environment:
      - CATA_LOG_PASSWORD=testwithdb1234 # gitleaks:allow
      - CATA_LOG_ALLOWED_HOSTS=["127.0.0.1","localhost"]
      - CATA_LOG_EXTERNAL_DATABASE_URL=postgresql+pg8000://user:db_passwd@db/cata-log
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
