services:
  cata-log-hub:
    image: cata-log-hub:latest
    container_name: cata-log
    volumes:
      - cata-log-storage:/mnt/storage
      - cata-log-db:/mnt/db
      - cata-log-logs:/var/log/cata-log
      - cata-log-plugins:/mnt/plugins
    ports:
      - 2424:8000
    environment:
      - CATA_LOG_PASSWORD=SafE_pAs5w0rd # setting no password makes authentication impossible #gitleaks:allow
      - CATA_LOG_ALLOWED_HOSTS=["127.0.0.1","localhost"] # hostnames that are allowed to serve this instance
    restart: unless-stopped

volumes:
  cata-log-storage:
  cata-log-db:
  cata-log-logs:
  cata-log-plugins:
